<?php
$tr = Zend_Registry::get('Zend_Translate');
?>

<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'comic', 'action' => 'add-character'), '', true); ?>"><?php echo $tr->_("Add character");?></a>

<?php
$l = $this->characters;
if (is_array($l) && !empty($l))
{
  $d = new Zend_Date();

  echo '<table width="100%">' . "\n";

  echo '<col width="1" />' . "\n";
  echo '<col width="1" />' . "\n";
  echo '<col width="100%" />' . "\n";


  echo '<tr>';
  echo '<td align="center">' . $tr->_("ID") . '</td>';
  echo '<td align="center">' . $tr->_("Image") . '</td>';
  echo '<td align="center">' . $tr->_("Description") . '</td>';
  echo "</tr>\n";

  $even = true;

  for($i=0; $i<count($l); $i++)
  {
    $class = null;

    if($even)
    {
      $class = 'even ';
    }
    else
    {
      $class = 'odd ';
    }

    $id = $l[$i]['id'];
    $name = $this->escape($l[$i]['name']);
    $desc = $l[$i]['descr'];

    $img = $l[$i]['md5sum'];
    $img_link = $this->url(array('module' => 'default', 'controller' => 'comic', 'action' => 'display-character', 'id' => $img, 'name' => $name), '', true);

    $edit_link = $this->url(array('controller' => 'comic', 'action' => 'edit-character', 'id' => $id), '', true);

    echo sprintf('<tr class="%s">', trim($class));
    echo '<td align="center"><a href="' . $edit_link . '">' . $id .  '</a></td>';
    echo '<td align="center" class="character"><img src="' . $img_link . '" alt="' . $name . '" class="character-image" /><br />' . $name . '</td>';
    echo '<td align="left" class="character-description">' . $desc. '</td>';
    echo "</tr>\n";

    $even = !$even;
  }

  echo "</table>\n";

}
else
{
  echo $tr->_("No characters");
}
?>