/* CSS RESET: */
*
{
  margin: 0;
  padding: 0;
}

/******************************************************************************/

/* CSS */

body
{
  background-color: #eee;
}

h1, h2, h3, h4
{
  padding-top: 0.5em;
  clear: both;
}

.even
{
  background-color: #efe;
}

.odd
{
  background-color: #ffe;
}

/******************************************************************************/

/* Header */

#header
{
  display: block;
  clear: both;
}

#header #menu ul
{
	clear: both;
	margin: 0;
	padding: 0;
	list-style: none;
	border: none;
	white-space: nowrap;
}

#header #menu ul li
{
	position: relative;
	white-space: nowrap;
	border: none;
	padding: 0;
	background-repeat: no-repeat;
	height: 100%;
	display: inline;
	padding-right: 1em;
}

#header #menu ul li a
{
  text-decoration: none;
  font-weight: bolder;
}


/* Admin menu */
#header #admin-menu ul
{
	clear: both;
	margin: 0;
	padding: 0;
	list-style: none;
	border: none;
	white-space: nowrap;
}

#header #admin-menu ul li
{
	position: relative;
	white-space: nowrap;
	border: none;
	padding: 0;
	background-repeat: no-repeat;
	height: 100%;
	display: inline;
}

/******************************************************************************/

/* Footer */

#footer
{
  text-align: right;
}

/******************************************************************************/

/* Posts */

#posts .entry
{
  display: block;
  border: 1px solid #000;
}

#posts .entry-subject
{
  display: block;
  border-bottom: 1px solid #000;
  background-color: #ddd;
}

#posts .entry-author
{
  display: block;
  border-top: 1px solid #000;
  background-color: #ddd;
}

/******************************************************************************/

/* Content */
#content
{
  margin: auto auto;
  width: 60em;
}

#menu
{
  background-color: #fed;
}

/******************************************************************************/

/* Comic */

.comic-navigation
{
  display: block;
  clear: both;
}

.comic-navigation ul
{
	clear: both;
	margin: 0;
	padding: 0;
	list-style: none;
	border: none;
	white-space: nowrap;
}

.comic-navigation ul li
{
	position: relative;
	white-space: nowrap;
	border: none;
	padding: 0;
	background-repeat: no-repeat;
	display: inline;
	padding-right: 1em;
}

.comment-added
{
  padding-right:1em;
}

#logout a
{
  color: #f11;
}