<?php
$tr = Zend_Registry::get('Zend_Translate');

$d = new Zend_Date();
$d->setTimestamp($this->info['upublished']);
?>

<h2><?php echo $tr->_("Edit comic");?></h2>
<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'comic', 'action' => 'change', 'id' => $this->id), '', true);?>"><?php echo $tr->_("Change comic image");?></a>
<br />

<?php echo $this->info['author'];?> <?php echo $d->toString($this->dateformat);?> <?php echo $this->info['name'];?>

<br />

<?php echo $this->form;?>
