<?php
$tr = Zend_Registry::get('Zend_Translate');

$posts = $this->posts;
?>

<h2><?php echo $tr->_("Front page");?></h2>

<div id="intro">
<?php echo $this->introtext;?>
</div>

<div id="posts" class="external-urls">
<?php
if(is_array($posts) && !empty($posts))
{
  $d = new Zend_Date();

  for($i=0; $i<count($posts); $i++)
  {
    $subject = $this->escape($posts[$i]['subject']);
    $txt = $posts[$i]['content'];
    $author = $this->escape($posts[$i]['name']);
    $d->setTimestamp($posts[$i]['uadded']);
    
    echo '<div class="entry">';
    echo '<div class="entry-subject"><h3>';
    echo $subject;
    echo '</h3></div>';
    echo '<div class="entry-content">';
    echo $txt;
    echo '</div>';

    echo '<div class="entry-author">';
    echo "$author " . $d->toString($this->dateformat);
    echo '</div>';

    echo "</div>\n";
  } // /for
}
else
{
  echo $tr->_('No posts');
}
?>
</div>

<div id="statistics">

<div id="comics-latest-comments" class="statistics">
<?php
$l = $this->comments;

if(is_array($l) && !empty($l))
{
  echo $tr->_('Latest comic comments');

  echo '<table width="100%">' . "\n";

  echo '<col width="1" />' . "\n";
  echo '<col width="100%" />' . "\n";

  echo '<tr>';
  echo '<td></td>';
  echo '<td></td>';
  echo "</tr>\n";

  $even = true;

  for($i=0; $i<count($l); $i++)
  {
    $class = null;

    if($even)
    {
      $class = 'even ';
    }
    else
    {
      $class = 'odd ';
    }

    $id = $l[$i]['comicid'];
    $title = $this->escape($l[$i]['title']);
    $comment = $this->escape($l[$i]['comment']);
    $country = $l[$i]['country'];

    $link = $this->url(array('controller' => 'comic', 'action' => 'index', 'id' => $id, 'name' => $title), '', true);

    echo sprintf('<tr class="%s">', trim($class));
    echo '<td align="center"><a href="' . $link . '">' . str_replace(' ', '&nbsp;', $title) . '</a></td>';
    echo '<td align="left"><img src="/images/flags18x12/' . $country . '.png" alt="' . $country. '" width="18" height="12" /> ' . $comment . '</td>';
    echo "</tr>\n";

    $even = !$even;
  }

  echo "</table>\n";
}
?>
</div>


<div id="comics-top" class="statistics">
<?php
$l = $this->topcomics;

if(is_array($l) && !empty($l))
{
  echo $tr->_('Top ten comics');

  echo '<table width="100%">' . "\n";

  echo '<col width="1" />' . "\n";
  echo '<col width="100%" />' . "\n";

  echo '<tr>';
  echo '<td></td>';
  echo '<td></td>';
  echo "</tr>\n";

  $even = true;

  for($i=0; $i<count($l); $i++)
  {
    $class = null;

    if($even)
    {
      $class = 'even ';
    }
    else
    {
      $class = 'odd ';
    }

    $id = $l[$i]['id'];
    $name = $this->escape($l[$i]['name']);
    $rating = $l[$i]['avgrate'];

    $link = $this->url(array('controller' => 'comic', 'action' => 'index', 'id' => $id, 'name' => $name), '', true);

    echo sprintf('<tr class="%s">', trim($class));
    echo '<td align="center">' . $rating . '</td>';
    echo '<td align="left"><a href="' . $link . '">' . $name . '</a></td>';
    echo "</tr>\n";

    $even = !$even;
  }

  echo "</table>\n";
}
?>
</div>

<div id="comics-bottom" class="statistics">
<?php
$l = $this->bottomcomics;

if(is_array($l) && !empty($l))
{
  echo $tr->_('Worst ten comics');

  echo '<table width="100%">' . "\n";

  echo '<col width="1" />' . "\n";
  echo '<col width="100%" />' . "\n";

  echo '<tr>';
  echo '<td></td>';
  echo '<td></td>';
  echo "</tr>\n";

  $even = true;

  for($i=0; $i<count($l); $i++)
  {
    $class = null;

    if($even)
    {
      $class = 'even ';
    }
    else
    {
      $class = 'odd ';
    }

    $id = $l[$i]['id'];
    $name = $this->escape($l[$i]['name']);
    $rating = $l[$i]['avgrate'];

    $link = $this->url(array('controller' => 'comic', 'action' => 'index', 'id' => $id, 'name' => $name), '', true);

    echo sprintf('<tr class="%s">', trim($class));
    echo '<td align="center">' . $rating . '</td>';
    echo '<td align="left"><a href="' . $link . '">' . $name . '</a></td>';
    echo "</tr>\n";

    $even = !$even;
  }

  echo "</table>\n";
}
?>
</div>

</div> <!-- statistics -->