<?php
$tr = Zend_Registry::get('Zend_Translate');
?>
<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'change-password'), '', true); ?>"><?php echo $tr->_("Change password");?></a>

<h2><?php echo $tr->_("Config.ini");?></h2>
<?php echo sprintf($tr->_("Name: '%s'"), $this->config->name);?><br />
<?php echo sprintf($tr->_("Slogan: '%s'"), $this->config->slogan);?><br />
<?php echo sprintf($tr->_("Debug mode: '%s'"), $this->config->debug);?><br />
<?php echo sprintf($tr->_("Language: '%s'"), $this->config->language);?><br />
<?php echo sprintf($tr->_("E-mail sender address: '%s'"), $this->config->sender);?><br />
<?php echo sprintf($tr->_("Cache directory: '%s'"), $this->config->directory);?><br />
<?php echo sprintf($tr->_("Date format: '%s'"), $this->config->dateformat);?><br />
<?php echo sprintf($tr->_("Akismet key: '%s'"), $this->config->plugin->akismet->key);?><br />
<?php echo sprintf($tr->_("Google analytics key: '%s'"), $this->config->plugin->googleanalytics->key);?><br />

