<?php
$tr = Zend_Registry::get('Zend_Translate');
?>
<a rel="nofollow" href="<?php echo $this->url(array('controller' => 'guestbook', 'action' => 'add'), '', true); ?>"><?php echo $tr->_("Add new guestbook entry");?></a>
<br />
<h2><?php echo $tr->_("Guestbook");?></h2>
<div id="guestbook" class="external-urls">
<?php
$l = $this->entries;

if(is_array($l) && !empty($l))
{
  $d = new Zend_Date();
  $even = true;

  for($i=0; $i<count($l); $i++)
  {
    $class = null;

    if($even)
    {
      $class = 'even ';
    }
    else
    {
      $class = 'odd ';
    }

    $country = $l[$i]['country'];
    $country = empty($country) ? 'unknown' : $country;

    $name = $this->escape($l[$i]['name']);
    $q = nl2br($this->escape($l[$i]['question']));
    $a = $l[$i]['answer'];
    $d->setTimestamp($l[$i]['uadded']);

    echo sprintf('<div class="%s">', trim($class));

    echo '<div class="asker">';

    echo '<img src="/images/flags18x12/' . $country . '.png" alt="' . $country. '" width="18" height="12" />';
    echo " $name ";
    echo $d->toString($this->dateformat);
    echo ' (' . sprintf($tr->_("%s ago"), $this->relativetime($l[$i]['uadded'])) . ')';
    echo '</div>';

    echo '<div class="question">' . $q . '</div>';

    if(!empty($a))
    {
      echo '<div class="answer">' . $a . '</div>';
    }

    echo "</div>\n";

    $even = !$even;
  }

}
else
{
  echo $tr->_("No guestbook entries");
}
?>
</div>