<?php
$tr = Zend_Registry::get('Zend_Translate');

// Custom CSS
$css = <<<CSS
  #fieldset-mail
  {
    display: none;
    visibility: hidden;
  }

  .zend_form
  {
    margin-top: -2em;
  }
CSS;
$this->headStyle()->appendStyle($css);
?>
<h2><?php echo $tr->_("Add new guestbook entry");?></h2>
<div id="guestbook-form">
  <?php echo $this->gbform;?>
</div>

<h2><?php echo $tr->_("Guestbook");?></h2>
<div id="guestbook">
<?php
$l = $this->entries;

if(is_array($l) && !empty($l))
{
  $even = true;

  for($i=0; $i<count($l); $i++)
  {
    $class = null;

    if($even)
    {
      $class = 'even ';
    }
    else
    {
      $class = 'odd ';
    }

    $name = $this->escape($l[$i]['name']);
    $q = nl2br($this->escape($l[$i]['question']));
    $a = $l[$i]['answer'];
    $published = $this->escape($l[$i]['added']);
    $published = str_replace(' ', '&nbsp;', $published);


    echo sprintf('<div class="%s">', trim($class));
    echo '<div class="asker">' . "$name $published" . '</div>';
    echo '<div class="question">' . $q . '</div>';
    if(!empty($a))
    {
      echo '<div class="answer">' . $a . '</div>';
    }
    echo "</div>\n";

    $even = !$even;
  }

}
else
{
  echo $tr->_("No guestbook entries");
}
?>
</div>